kadai0129/kadai/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kadai_app.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

kadai0129/kadai_app/urls.py
from django.urls import path

from . import views

app_name = 'kadai_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name = "index"),
    path('unlogin/', views.UnloginView.as_view(), name = "unlogin"),

    path('inquiry/', views.InquiryView.as_view(), name = "inquiry"),
    
    path('play-list/', views.PlayListView.as_view(), name= "play_list"),
    path('play-detail/<int:pk>/', views.PlayDetailView.as_view(), name = "play_detail"),
    path('play-create/', views.PlayCreateView.as_view(), name = "play_create"),
    path('play-update/<int:pk>/', views.PlayUpdateView.as_view(), name = "play_update"),
    path('play-delete/<int:pk>/', views.PlayDeleteView.as_view(), name = "play_delete"),
    path('group-list/', views.GroupListView.as_view(), name= "group_list"),
    path('group-create/', views.GroupCreateView.as_view(), name ="group_create"),
    path('group-detail/<str:group>/', views.GroupDetailView.as_view(), name = "group_detail"),
    path('group-update/<str:group>/', views.GroupCreate2View.as_view(), name = "group_update"),
    path('group-music-create/', views.GroupMusicCreateView.as_view(), name ="group_music_create"),
    path('searchpage/', views.SearchpageView.as_view(), name = "searchpage"),
    path('mypage/', views.MyPageView.as_view(), name= "mypage"),
    path('intro/', views.IntroView.as_view(), name = "intro"),
    path('play/', views.PlayView.as_view(), name = "play"),
    path('userpage/', views.UserpageView.as_view(), name = "userpage"),
    path('playlistname/', views.PlaylistnameView.as_view(), name= "playlistname"),
    # コメント追加用のhtml（htmlファイル自体はplay_detailに組み込まれる）
    path('comment/create/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'),
    path('likes/form/<int:play_pk>', views.IineCreateView.as_view(), name='likes_form'),
    path('userpage/<int:pk>', views.UserDetailView.as_view(), name ="userpage"),
    path('follow/form/<int:fuser_pk>', views.FollowCreateView.as_view(), name='follow_form'),

    path('user-update/<int:pk>/', views.UserinfoUpdateView.as_view(), name = "user_update"),
    path('play-remake/<int:pk>/', views.PlayRemakeView.as_view(), name = "play_remake"),
]

kadai0129/kadai_app/models.py
import os

from django.db import models

from accounts.models import CustomUser

from django.core.validators import FileExtensionValidator

import sox

class Play(models.Model):
    """投稿した曲モデル"""
    name = 'song'
    TAG = (
        ('A', 'Japan'),
        ('B', 'America'),
        ('C', 'China'),
    )


    user = models.ForeignKey(CustomUser, verbose_name = 'ユーザー', on_delete = models.PROTECT)
    title = models.CharField(verbose_name = 'タイトル', max_length = 40, default = name)
    attach1 = models.FileField(verbose_name='添付ファイル', default = 'audio0.mp3')
    about_song = models.TextField(verbose_name = '説明', max_length = 400, default = name)
    tag = models.CharField(verbose_name = 'タグ', max_length = 10, default = name,blank=True, null=True)
    music_photo = models.ImageField(verbose_name='ジャケット写真', upload_to='images', blank=True, null=True)
    picth_num = models.IntegerField(default = 0)
    iine_num = models.IntegerField(default = 0, verbose_name='いいね')
    loaded_num = models.IntegerField(default=0, verbose_name='再生数')

    parent_play = models.IntegerField(verbose_name='編集元楽曲キー', default=0)

    created_at = models.DateTimeField(verbose_name = '作成日時', auto_now_add = True)
    update_at = models.DateTimeField(verbose_name = '更新日時', auto_now = True)

    class Meta:
        verbose_name_plural = 'Play'
        constraints = [
            models.UniqueConstraint(
                fields=["user", "title"],
                name="play_unique"
            ),
        ]

    def __str__(self):
        return self.title

class Grouper(models.Model):
    """プレイリスト作成モデル"""
    name = 'playlist'
    user = models.ForeignKey(CustomUser, verbose_name = 'ユーザー', on_delete = models.PROTECT)
    title = models.CharField(verbose_name = 'タイトル', max_length = 40, default = name, unique=True,)
    tag = models.CharField(verbose_name = 'タグ', max_length = 10, default = name,blank=True, null=True)
    music_photo = models.ImageField(verbose_name='ジャケット写真', upload_to='images', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name = '作成日時', auto_now_add = True)
    update_at = models.DateTimeField(verbose_name = '更新日時', auto_now = True)

    class Meta:
        verbose_name_plural = 'Grouper'
        constraints = [
            models.UniqueConstraint(
                fields=["user", "title"],
                name="group_unique"
            ),
        ]
    def __str__(self):
        return self.title

class Grouped(models.Model):
    """曲追加モデル"""

    name = 's'
    user = models.ForeignKey(CustomUser, verbose_name = 'ユーザー', on_delete = models.PROTECT)
    group = models.ForeignKey(Grouper, on_delete=models.CASCADE)
    upload_music = models.ForeignKey(Play, related_name='music',verbose_name = '投稿した曲', on_delete = models.CASCADE, blank=True, null=True)
    douwload_music = models.FileField(verbose_name='ダウンロードした曲', upload_to='upmusic', validators=[FileExtensionValidator(['wav', 'mp3', 'alf',])], blank=True, null=True)
    priority = models.IntegerField(verbose_name='優先度', default=0)
    created_at = models.DateTimeField(verbose_name = '作成日時', auto_now_add = True)
    update_at = models.DateTimeField(verbose_name = '更新日時', auto_now = True)

    class Meta:
        verbose_name_plural = 'Grouped'
        constraints = [
            models.UniqueConstraint(
                fields=["user", "group", "upload_music"],
                name="grouped_unique"
            ),
        ]
    def __str__(self):
        return str(self.group)

class Comment(models.Model):
    """記事に紐づくコメント"""

    text = models.TextField('')
    target = models.ForeignKey(Play, on_delete=models.CASCADE, verbose_name='対象楽曲')

class Likes(models.Model):
    """いいねモデル"""
    player = models.ForeignKey(Play, on_delete=models.CASCADE, verbose_name='対象楽曲')
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT, verbose_name='いいねしたユーザー')

    class Meta:
        verbose_name_plural = 'Likes'
    
    def __str__(self):
        return self.player

class Follow(models.Model):
    """フォロー機能"""
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT, verbose_name='フォロワー')

    followuser = models.ForeignKey(CustomUser, on_delete=models.CASCADE,
    verbose_name='フォロー', related_name='followuser')

    class Meta:
        verbose_name_plural = 'Follow'
    
    def __str__(self):
        return str(self.followuser)

class Userlog(models.Model):
    """ユーザー登録後の追加情報（自己紹介等）"""
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT, verbose_name='基本情報')

    intro = models.CharField(verbose_name='自己紹介', max_length=200, default='こんにちは！')#*

    GENRE = (
        ('A', 'Japan'),
        ('B', 'America'),
        ('C', 'China'),
    )

    GOOD_INS = (
        ('D', 'Dapan'),
        ('E', 'Emerica'),
        ('F', 'Fhina'),
    )

    genre = models.CharField(verbose_name='好きな音楽ジャンル', choices = GENRE, max_length=20)

    avatar_photo = models.ImageField(verbose_name='アバター写真', upload_to='images', blank=True, null=True)

    good_instrument = models.CharField(verbose_name='得意な楽器', choices=GOOD_INS, max_length=20)

    class Meta:
        verbose_name_plural = 'Userlog'
    
    def __str__(self):
        return str(self.intro)

class Playfollower(models.Model):
    """派生した楽曲を格納するモデル"""
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT, verbose_name='フォロワー')

    current_play = models.ForeignKey(Play, on_delete=models.CASCADE,
    verbose_name='親', related_name='current_play')

    child_play = models.ForeignKey(Play, on_delete=models.CASCADE, verbose_name='子', related_name='child_play')

    class Meta:
        verbose_name_plural = 'Playfollower'
    
    def __str__(self):
        return str(self.child_play)

kadai0129/kadai_app/forms.py
from django import forms
from django.core.mail import EmailMessage
from .models import Play, Grouper, Grouped, Comment, Likes, Follow, Userlog

class UserlogForm(forms.ModelForm):
    class Meta:
        model = Userlog
        fields = ('intro', 'genre', 'avatar_photo', 'good_instrument')
        
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'

class InquiryForm(forms.Form):
    name = forms.CharField(label = 'お名前', max_length = 30)
    email = forms.EmailField(label = 'メールアドレス')
    title = forms.CharField(label = 'タイトル', max_length = 30)
    message = forms.CharField(label = 'メールアドレス', widget = forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = ' お名前をここに入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください'


    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject ='お問い合わせ{}'.format(title)
        message ='送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = 'admin@example.com'
        to_list = [
            'test@example.com'
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject =subject, body = message, from_email = from_email, to = to_list, cc = cc_list)
        message.send()

class PlayCreateForm(forms.ModelForm):
    """ 楽曲投稿フォーム """
    class Meta:
        model = Play
        fields = ('title', 'attach1', 'about_song','music_photo','tag','picth_num')
        
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'

class PlayRemakeForm(forms.ModelForm):
    """ remake楽曲投稿フォーム """
    class Meta:
        model = Play
        fields = ('title', 'about_song','music_photo','tag','picth_num')
        
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'

class GroupCreateForm(forms.ModelForm):
    """ プレイリスト作成フォーム """
    class Meta:
        model = Grouper
        fields = ('title', 'music_photo','tag')
        
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            id = kwargs.get("instance").user.id
            self.fields['title'].queryset = Grouper.objects.filter(user_id=id)
            # for field in self.fields.values():
            #     field.widget.attrs['class'] = 'form-control'

class GroupMusicCreateForm(forms.ModelForm):
    """ 曲追加フォーム """
    class Meta:
        model = Grouped
        fields = ()
        # fields = ('upload_music', 'douwload_music', 'group',)
        
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            az = self.kwargs.get("instance").user
            self.fields['group'].queryset = Grouper.objects.filter(user=az)

class GroupMusicCreate2Form(forms.ModelForm):
    class Meta:
        model = Grouped
        fields=()

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'

class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

class IineCreateForm(forms.ModelForm):
    class Meta:
        model = Likes
        fields = ()

class FollowCreateForm(forms.ModelForm):
    class Meta:
        model = Follow
        fields = ()

kadai0129/kadai_app/templates/group_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <p id="test"></p>
                <button class="btn btn-primary" type="submit">作成</button>
            </form>
            <!-- <input id="button1" type="button" value="plus" onclick="plus()"> -->
            <!-- <script type="text/javascript">
                function plus(){
                    var hrNode = document.createElement('hr');
                    test.appendChild(hrNode);
                    var inputNode = document.createElement('input');
                    inputNode.type= "text";
                    // inputNode.autocomplete = "on";
                    // inputNode.list= "select_name";
                    // inputNode.value= "{{ value }}";
                    test.appendChild(inputNode);
                }
                var test = document.getElementById('test');
                var inputNode = document.createElement('input');
                inputNode.type= "text";
                test.appendChild(inputNode);                
            </script> -->
        </div>
    </div>
</div>
{% endblock %}

<!-- ・html内部でjavascriptを使い、formを任意で増やせるようにする
・増やした数をjavascriptに
・javascriptでstring(x)で(name=str型の数字)で認識できるようにする（html書き換え）

・html内部では(name= '数字' )と記述（javascriptでインクリメントする）
・増やした回数をviewに渡す（材料種類に当たる）、
・viewにhtmlの中身をリストで渡す（name = 'namea_z'のzを数字で判断）
・viewで -->

kadai0129/kadai_app/templates/play_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block active_diary_list %}active{% endblock %}


{% block contents %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>
		Play
	</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="My Podcast template project">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap-4.1.2/bootstrap.min.css' %}">
	<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'plugins/colorbox/colorbox.css' %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/episodes.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/episodes_responsive.css' %}">

	<!-- CSS here -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
	<link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<!-- <link rel="stylesheet" href="css/responsive.css"> -->
	<style>
		.audio_img {
			object-fit: cover;
			margin: 20px 20px 20px 20px;
			width: 100px;
			height: 100px;
			border-radius: 6px;
		}
		.images {
			width: 80px;
			height: 80px;
			object-fit: cover;
		}
	</style>
</head>

<body>
	<div class="super_container">
		<!-- Home -->
		<div class="home">
			<div class="parallax_background parallax-window" data-parallax="scroll"
				data-image-src="{% static 'images/cover1.jpg' %}" data-speed="0.8"></div>
			<div class="home_container d-flex flex-column align-items-center justify-content-center">
				<div class="home_content">
					<div class="home_title">
						<h1>
							PLAY STATION
						</h1>
					</div>
				</div>
			</div>
		</div>

		<!--================ 再生機能 =================-->
		<section class="blog_area single-post-area section-padding">
			<div class="container">
				<div class="row">
					<div class="col-lg-8 posts-list">
						<div class="single-post">
							<div class="feature-img">
								<img class="img-fluid" src="img/blog/single_blog_1.png" alt="">
							</div>
							<div class="blog_details">
								<h2>
									{% if object.music_photo %}
									<img class="audio_img" src="{{ object.music_photo.url}}" alt="">
									{% else %}
									<img class="audio_img" src="{% static 'images/no_image2.jpg' %}" alt="">
									{% endif %}
									{{ object.title }}
								</h2>
								<div class="track track_home">
									<audio id="radio" class="audio_song" controls autoplay loop>
										あなたのブラウザーは <code>audio</code>要素をサポートしていません。
										<source src="{{ object.attach1.url }}">
									</audio>
								</div>

								<!-- 「イイネ」 -->
								<ul class="blog-info-link mt-3 mb-4">
									<li>
										<a href="{% url 'kadai_app:mypage' %}">
											<i class="fa fa-plus"></i>
											Add to Playlist
										</a>
									</li>
									<li>
										<a href="{% url 'kadai_app:play_remake' play.pk %}">
											<i class="fa fa-edit"></i>
											Remake
										</a>
									</li>
									<li>
										<a href="#">
											<i class="fa fa-share"></i>
											Share
										</a>
									</li>
									<!-- 曲の再生数 -->
									<li>再生数：{{ loadnum }}回</li>

									<!-- 追加 (viewの498行目のclassも追加)-->
									{% if parent_name_ob %}
									<li>親の楽曲：{{ parent_name_ob }}</li>
									{% endif %}


									<li>
										{% if user.is_authenticated %}
										<form action="{% url 'kadai_app:likes_form' play.pk %}" method="post">
											{% csrf_token %}
											<div class="button_like">
												<a href="#">
													<i class="fa fa-heart">
													</i>
													{{ iine_num }}
												</a>
												<button type="submit">Likes</button>
											</div>
										</form>
										{% endif %}
									</li>
								</ul>
							</div>
						</div>

						<!-- お気に入り登録・解除 -->
						<div class="blog-author">
							<div class="media align-items-center">
								<div class="media post_item">
									<div class="media-body">
										<ul class="blog-info-link mt-3 mb-4">
											<img src="{% static 'img/blog/author.png' %}" alt="">
											<p>
												<!-- 投稿者と同一人物じゃない場合 -->
												{% if user.pk != play.user.pk %}
											<form action="{% url 'kadai_app:follow_form' play.user.pk %}" method="post">
												{% csrf_token %}
												<div class="col text-center button_like">
													{% if flg %}
													<i class="fa fa-user-plus"></i>
													<button class="button_fill shows_button" type="submit">
														お気に入り登録
													</button>
													{% else %}
													<i class="fa fa-user-plus"></i>
													<button class="button_fill shows_button" type="submit">
														お気に入り解除
													</button>
													{% endif %}
												</div>
											</form>
											{% endif %}
											</a>
											</p>
										</ul>
									</div>
								</div>

								<!-- 概要欄 -->
								<div class="media-body">
									{% if user.pk != play.user.pk %}
									<a href="{% url 'kadai_app:userpage' play.user.pk %}">
										<h3>
											この曲は、 {{ play.user }} さんが投稿しました！
										</h3>
									</a>
									{% else %}
									<!-- ログインユーザーと同じだった場合マイページへ -->
									<a href="{% url 'kadai_app:mypage' %}">
										<h3>
											{{ user }}
										</h3>
									</a>
									{% endif %}
									<p>{{ object.about_song }}
									</p>
								</div>

								{% if user == object.user %}
								<a class="btn btn-success mt-5 mb-3" href="{% url 'kadai_app:play_update' object.pk %}">
									Adjust
								</a>
								<a class="btn btn-danger mt-5 ml-2 mb-3"
									href="{% url 'kadai_app:play_delete' object.pk %}">
									Delete
								</a>
								{% endif %}
							</div>
						</div>

						<!-- コメント機能 -->
						<div class="comments-area">
							<div class="comment-form">
								<h4>
									Leave a Comment
								</h4>
								<form action="{% url 'kadai_app:comment_create' play.pk %}" method="post">
									{% csrf_token %}
									{{ comment_form}}
									<div class="form-group">
										<button type="submit" class="button button-contactForm btn_1 boxed-btn">
											Send
										</button>
									</div>
								</form>
							</div>

							<h4>
								000 Comments
							</h4>
							{% for comment in play.comment_set.all %}
							<div class="comment-list">
								<div class="single-comment justify-content-between d-flex">
									<div class="user justify-content-between d-flex">
										<div class="thumb">
											<img src="{% static 'img/comment/comment_1.png' %}" alt="">
										</div>
										<div class="desc">
											<h5>
												<!-- 投稿者が本人じゃない場合は、ユーザーページへ -->
												{% if user.pk != user.pk %}
												<a href="{% url 'kadai_app:userpage' user.pk %}">
													{{ user }}
												</a>
												<!-- 投稿者が本人の場合は、マイページへ -->
												{% else %}
												<a href="{% url 'kadai_app:mypage' %}">
													{{ user }}
												</a>
												{% endif %}
											</h5>
											<p class="comment">
												{{ comment.text }}
											</p>
											<div class="d-flex justify-content-between">
												<div class="d-flex align-items-center">
													<p class="date">
														December 4, 2017 at 3:12 pm
													</p>
												</div>
												<div class="reply-btn">
													<a href="#" class="btn-reply text-uppercase">
														reply
													</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							{% endfor %}
						</div>
					</div>

					<!--tag-->
					<div class="col-lg-4">
						<div class="blog_right_sidebar">

							<aside class="single_sidebar_widget tag_cloud_widget">
								<h4 class="widget_title">Tag</h4>
								<ul class="list">
									<li><a href="#">Kpop</a></li>
									<li><a href="#">love</a></li>
									<li><a href="#">travel</a></li>
								</ul>
							</aside>

							<!-- 追加 (327行目まで)-->
							<aside class="single_sidebar_widget popular_post_widget">
								<h3 class="widget_title">Remake song</h3>
								{% if child_name_ob %}
								{% for item in child_name_ob %}
								<div class="media post_item">
									{% if item.child_play.music_photo %}
									<img class="images" src="{{ item.child_play.music_photo.url }}" alt="post">
									{% else %}
									<img class="images" src="{% static 'images/no_image2.jpg' %}" alt="post">
									{% endif %}
									<div class="media-body">
										<a href="{% url 'kadai_app:play_detail' item.child_play.pk %}">
											<h3>{{ item }}</h3>
										</a>
										<p>{{ item.child_play.user }}</p>
									</div>
								</div>
								{% endfor %}
								{% endif %}
							</aside>

							<aside class="single_sidebar_widget popular_post_widget">
								<h3 class="widget_title">Former song</h3>
								{% if parent_name_ob %}
								<div class="media post_item">
									{% if parent_name_ob.music_photo %}
									<img class="images" src="{{ parent_name_ob.music_photo.url }}" alt="post">
									{% else %}
									<img class="images" src="{% static 'images/no_image2.jpg' %}" alt="post">
									{% endif %}
									<div class="media-body">
										<a href="{% url 'kadai_app:play_detail' parent_name_ob.pk %}">
											<h3>{{ parent_name_ob }}</h3>
										</a>
										<p>{{ parent_name_ob.user }}</p>
									</div>
								</div>
								{% endif %}
							</aside>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--================ Blog Area end =================-->
	</div>

	<!-- JS here -->
	<script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
	<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/isotope.pkgd.min.' %}js"></script>
	<script src="{% static 'js/ajax-form.js' %}"></script>
	<script src="{% static 'js/waypoints.min.js' %}"></script>
	<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
	<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
	<script src="{% static 'js/scrollIt.js' %}"></script>
	<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/wow.min.js' %}"></script>
	<script src="{% static 'js/nice-select.min.js' %}"></script>
	<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/plugins.js' %}"></script>
	<script src="{% static 'js/gijgo.min.js' %}"></script>

	<!-- <script type="text/javascript">
		var idradio = document.getElementById('radio');
		idradio.addEventListener('ended', function () {
			var radionum = document.getElementById('loadednum');
			radionum.value +=1;
		});
	</script> -->

	<!--contact js-->
	<script>
		$('#datepicker').datepicker({
			iconsLibrary: 'fontawesome',
			icons: {
				rightIcon: '<span class="fa fa-caret-down"></span>'
			}
		});
		$('#datepicker2').datepicker({
			iconsLibrary: 'fontawesome',
			icons: {
				rightIcon: '<span class="fa fa-caret-down"></span>'
			}

		});
	</script>
</body>

</html>
{% endblock %}

kadai0129/kadai_app/templates/play_remake.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

kadai0129/kadai_app/templates/play_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">更新</button>
                <a class="btn btn-secondary ml-2" href="{% url 'kadai_app:play_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}